Pishraft/Pishraft/urls.py
from django.contrib import admin
from django.urls import include, path
#from django.conf import settings
#rom django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('user_profiles/',include('profiles.urls',namespace='user_profiles'))
] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Pishraft/accounts/urls.py
from django.urls import path 
from accounts import views
app_name = 'accounts'
urlpatterns = [

    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('verify/',views.UserVerifyCodeView.as_view(), name='verify_code'),
    path('logout/',views.UserLogoutView.as_view(),name='logout'),
]

Pishraft/home/urls.py
from django.urls import path
from home import views


app_name = 'home'
urlpatterns = [
    path('home_page_user/<int:id>/', views.HomeView.as_view(), name='home'),
    path('category/<slug:slug>/', views.HomeView.as_view(), name='home_slug'),
    path('',views.Normal_Home_View.as_view(),name='normalhome'),
    path('bucket/',views.BucketHome.as_view(),name='bucket'),
    path('download_obj_bucket/<str:key>/',views.Downlaod_Obj_Bucket.as_view(),name='download_obj_bucket'),
    path('delete_obj_bucket/<str:key>/',views.Delete_Obj_Bucket.as_view(),name='delete_obj_bucket'),
    path('<slug:slug>/',views.ProductDetailesView.as_view(),name='product'),
    
]

Pishraft/templates/base.html
<!DOCTYPE html>
<html lang="en" color-mode="light">
{% load static %}
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="Munix Ecommerce Mobile HTML Template" />
        <meta name="keywords" content="Munix Ecommerce Mobile HTML Template" />
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <meta name="apple-mobile-web-app-title" content="Munix">
        <meta name="msapplication-TileImage" content="{% static 'img/icon-144.png' %}">
        <link rel="icon" href="{% static 'img/favicon.png' %}" sizes="35x35" type="image/png">
        <title>{% block title %}{% endblock title %}</title>
        <!--Stylesheet--> 
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/lobibox.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <!-- Web App Manifest-->
        <style>
            .jumbotron{
                padding: 20px;
                margin-bottom: 20px;
                background-color: #e9ecef;
          }
        </style>
    </head>
    <body>
        
        
        <div class="jumbotron ">
            {% include 'inc/messages.html' %}
        </div>
        {% block content %}{% endblock content %}
        {% block login %}{% endblock login %}
        {% block otpverify %}{% endblock otpverify %}
        {% block add_username %}{% endblock add_username %}
        {% block bucket %}{% endblock bucket %}

    </body>	
        
    </html>

Pishraft/templates/bucket.html
{% extends 'base.html' %}

{% block content %}

<table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">name</th>
        <th scope="col">size</th>
        <th scope="col">download</th>
        <th scope="col">delete</th>
        </tr>
    </thead>
    
    <tbody>
        {% for bucket in get_buckets %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ bucket.Key }}</td>
        <td>{{ bucket.Size|filesizeformat }}</td>
        <td><a href="{% url 'home:download_obj_bucket' bucket.Key %}"> download </a></td>

        <td><a href="{% url 'home:delete_obj_bucket' bucket.Key %}"> delete </a></td>

      </tr>
      {% endfor %}

    </tbody>
  </table>
  {% endblock content %}

Pishraft/templates/normalhome.html
{% extends 'base.html' %}


{% block content %}
    

    
        <!-- Internet Connection -->
        <div class="alert" id="checkOnline"></div>
        <!-- Page loader -->
        <div id="loader-page">
            <div class="loader" id="line">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
              </div>
        </div>
        <!-- page content -->
        <main class="main-content flex-shrink-0">
            <!-- Header Area-->
            
            <!-- Footer -->
        <div class="footer-area">
            <ul class="h-100 d-flex align-items-center justify-content-between ps-0">
               
                
                <li>
                   <a href="{% url 'accounts:register' %}"> <i class="fa fa-user"></i> <span>ورود | ثبت نام</span> </a>
                </li> 
                
            </ul>
        </div>
        </main>

        <!-- template js files -->
        {% include 'inc/jstemplates.html' %}
        <!-- Progressive Web App -->
        <script src="js/pwa.js"></script>
        {% endblock content %}