Pishraft/Pishraft/urls.py
from django.contrib import admin
from django.urls import include, path
#from django.conf import settings
#rom django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('user_profiles/',include('profiles.urls',namespace='user_profiles'))
] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Pishraft/accounts/urls.py
from django.urls import path 
from accounts import views
app_name = 'accounts'
urlpatterns = [

    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('verify/',views.UserVerifyCodeView.as_view(), name='verify_code'),
    path('logout/',views.UserLogoutView.as_view(),name='logout'),
]

Pishraft/home/urls.py
from django.urls import path
from home import views


app_name = 'home'
urlpatterns = [
    path('home_page_user/<int:id>/', views.HomeView.as_view(), name='home'),
    path('category/<slug:slug>/', views.HomeView.as_view(), name='home_slug'),
    path('',views.Normal_Home_View.as_view(),name='normalhome'),
    path('bucket/',views.BucketHome.as_view(),name='bucket'),
    path('download_obj_bucket/<str:key>/',views.Downlaod_Obj_Bucket.as_view(),name='download_obj_bucket'),
    path('delete_obj_bucket/<str:key>/',views.Delete_Obj_Bucket.as_view(),name='delete_obj_bucket'),
    path('<slug:slug>/',views.ProductDetailesView.as_view(),name='product'),
    
]

Pishraft/profiles/urls.py
from django.urls import path
from profiles import views

app_name = 'user_profiles'

urlpatterns = [
    path('profiles/<int:id>/',views.UserProfileView.as_view(),name='profile'),
]

Pishraft/templates/inc/footer.html
{% load static %}

<div class="footer-area">
    <ul class="h-100 d-flex align-items-center justify-content-between ps-0">
        <li class="active">
            {% for user in users %}
            <a href="{% url 'home:home' user.id %}"> <i class="fa fa-home"></i> <span> خانه</span> </a>
        </li>
        <li>
            <a href="my-order.html"> <i class="fa fa-shopping-bag"></i> <span>محصولات‌</span> </a>
        </li>
        <li>
            <a href="cart.html"> <i class="fa fa-heart"></i> <span> نشان شده ها</span></a>
        </li>
            <li>
                
            <a href="{% url 'user_profiles:profile' user.id %} "> <i class="fa fa-user"></i> <span>پروفایل</span> </a>
           
            </li>
                {% endfor %}

    </ul>
</div>
</main>

Pishraft/templates/inc/jstemplates.html
{% load static %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/lobibox.js' %}"></script>
<script src="{% static 'js/notification-custom-script.js' %}"></script>
<script src="{% static 'js/custom-scripts.js' %}"></script>

Pishraft/templates/inc/menu-nav.html
{% load static %}
<div class="sidebar-nav py-3">
    <div class="container">
       <div class="row align-items-center justify-content-between">
         <div class="header-logo col-auto">
            <a class="navbar-brand">
                <img src="{% static 'img/logo-white.png' %}" class="navbar-brand-img" alt="logo">
            </a>
         </div> 
         <div class="col-auto pe-0">
            <button class="btn navbar-toggler navbar-menu-toggler icon-boxed rounded-start"><i class="fa fa-times"></i></button>
        </div> 
       </div>

       <div class="row">
        <div class="col">
          <ul class="sidebar-menu flex-column">
              <li class="header-menu">
                  <span>منو</span>
              </li>
              <li><a href="home.html"> <i class="fa fa-home"></i> <span>خانه</span></a></li>
              <li><a href="catagory.html"> <i class="fas fa-layer-group"></i> <span>دسته بندی ها</span></a></li>
              <li><a href="wishlist.html"> <i class="fa fa-heart"></i> <span> علاقه مندیها</span> </a></li>
              <li><a href="cart.html"> <i class="fa fa-shopping-bag"></i> <span>خرید</span> </a></li>
              <li><a href="settings.html"> <i class="fa fa-cog rotatein animate__rotateIn"></i> <span>تنظیمات</span> </a></li>
              <li><a href="all-pages.html"> <i class="fa fa-file-alt"></i> <span>صفخات</span> </a></li>
              {% if request.user.is_authenticated %}
              <li><a href="{% url 'accounts:logout' %}" class="text-color15"> <i class="fas fa-sign-out-alt"></i><span>خروج</span></a></li>
              {% endif %}
            </ul>
        </div>
     </div>
     <div class="row copyright-info">
        <div class="col">
           <p>© 1400 Munix - همه حقوق محفوظ است.</p>
        </div>
    </div>
 </div>
</div>

Pishraft/templates/inc/messages.html
{% if messages %}

    {% for msg in messages %}
        <p>{{ msg }}</p>
    {% endfor %}

{% endif %}
    

Pishraft/templates/inc/page-loader.html
<div id="loader-page">
    <div class="loader" id="line">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </div>
</div>